-- liquibase formatted sql
-- 2022-12-22 20:00:00 VN
-- changeset trungkien.nguyen:V202212222000_init_master_database_data
INSERT
IGNORE INTO FeedBackType (name, slug)
VALUES  (N'Phản hồi lỗi hệ thống', 'phan-hoi-loi-he-thong'),
    (N'Phản hồi dịch vụ', 'phan-hoi-dich-vu'),
    (N'Loại phản hồi 1', 'loai-phan-hoi-1'),
    (N'Loại phản hồi 2', 'loai-phan-hoi-2'),
    (N'Loại phản hồi 3', 'loai-phan-hoi-3'),
    (N'Loại phản hồi 4', 'loai-phan-hoi-4'),
    (N'Loại phản hồi 5', 'loai-phan-hoi-5'),
    (N'Loại phản hồi 6', 'loai-phan-hoi-6'),
    (N'Loại phản hồi 7', 'loai-phan-hoi-7'),
    (N'Loại phản hồi 8', 'loai-phan-hoi-8'),
    (N'Loại phản hồi 9', 'loai-phan-hoi-9'),
    (N'Loại phản hồi 10', 'loai-phan-hoi-10'),
    (N'Loại phản hồi 11', 'loai-phan-hoi-11'),
    (N'Loại phản hồi 12', 'loai-phan-hoi-12'),
    (N'Loại phản hồi 13', 'loai-phan-hoi-13'),
    (N'Loại phản hồi 14', 'loai-phan-hoi-14'),
    (N'Loại phản hồi 15', 'loai-phan-hoi-15');

INSERT
IGNORE INTO FeedBack (title, slug, content, userId, feedBackTypeId)
VALUES (N'Phản hồi hệ thống nước hư', 'phan-hoi-he-thong-nuoc-hu', 'Hệ thống nước của phòng D01 đang bị hư. Cần sửa gấp', 1, 2),
    (N'Phản hồi hệ thống điện hư', 'phan-hoi-he-thong-dien-hu', 'Hệ thống điện của phòng D02 đang bị hư. Cần sửa gấp', 2, 2),
    (N'Phản hồi hệ thống còi báo động hư', 'phan-hoi-he-thong-coi-bao-dong-hu', 'Hệ thống còi báo động hư của phòng D03 đang bị hư. Cần sửa gấp', 3, 2),
    (N'Hệ thống không bình luận được', 'he-thong-khong-binh-luan-duoc', 'Hệ thống web không thể bình luận được', 5, 1),
     (N'Tiêu đề phản hồi 1', 'tieu-de-phan-hoi-1', 'Nội dung phản hồi 1', 1, 1),
     (N'Tiêu đề phản hồi 2', 'tieu-de-phan-hoi-2', 'Nội dung phản hồi 2', 2, 2),
     (N'Tiêu đề phản hồi 3', 'tieu-de-phan-hoi-3', 'Nội dung phản hồi 3', 3, 1),
     (N'Tiêu đề phản hồi 4', 'tieu-de-phan-hoi-4', 'Nội dung phản hồi 4', 4, 2),
     (N'Tiêu đề phản hồi 5', 'tieu-de-phan-hoi-5', 'Nội dung phản hồi 5', 1, 3),
     (N'Tiêu đề phản hồi 6', 'tieu-de-phan-hoi-6', 'Nội dung phản hồi 6', 1, 4),
     (N'Tiêu đề phản hồi 7', 'tieu-de-phan-hoi-7', 'Nội dung phản hồi 7', 1, 5),
     (N'Tiêu đề phản hồi 8', 'tieu-de-phan-hoi-8', 'Nội dung phản hồi 8', 1, 6),
     (N'Tiêu đề phản hồi 9', 'tieu-de-phan-hoi-9', 'Nội dung phản hồi 9', 1, 7),
     (N'Tiêu đề phản hồi 10', 'tieu-de-phan-hoi-10', 'Nội dung phản hồi 10', 1, 8),
     (N'Tiêu đề phản hồi 11', 'tieu-de-phan-hoi-11', 'Nội dung phản hồi 11', 1, 9),
     (N'Tiêu đề phản hồi 12', 'tieu-de-phan-hoi-12', 'Nội dung phản hồi 12', 1, 10),
     (N'Tiêu đề phản hồi 13', 'tieu-de-phan-hoi-13', 'Nội dung phản hồi 13', 1, 11),
     (N'Tiêu đề phản hồi 14', 'tieu-de-phan-hoi-14', 'Nội dung phản hồi 14', 1, 12),
     (N'Tiêu đề phản hồi 15', 'tieu-de-phan-hoi-15', 'Nội dung phản hồi 15', 1, 13),
     (N'Tiêu đề phản hồi 16', 'tieu-de-phan-hoi-16', 'Nội dung phản hồi 16', 2, 14),
     (N'Tiêu đề phản hồi 17', 'tieu-de-phan-hoi-17', 'Nội dung phản hồi 17', 2, 15),
     (N'Tiêu đề phản hồi 18', 'tieu-de-phan-hoi-18', 'Nội dung phản hồi 18', 2, 16),
     (N'Tiêu đề phản hồi 19', 'tieu-de-phan-hoi-19', 'Nội dung phản hồi 19', 2, 17),
     (N'Tiêu đề phản hồi 20', 'tieu-de-phan-hoi-20', 'Nội dung phản hồi 20', 2, 1),
     (N'Tiêu đề phản hồi 21', 'tieu-de-phan-hoi-21', 'Nội dung phản hồi 21', 1, 2),
     (N'Tiêu đề phản hồi 22', 'tieu-de-phan-hoi-22', 'Nội dung phản hồi 22', 1, 3),
     (N'Tiêu đề phản hồi 23', 'tieu-de-phan-hoi-23', 'Nội dung phản hồi 23', 1, 4),
     (N'Tiêu đề phản hồi 24', 'tieu-de-phan-hoi-24', 'Nội dung phản hồi 24', 2, 5),
     (N'Tiêu đề phản hồi 25', 'tieu-de-phan-hoi-25', 'Nội dung phản hồi 25', 2, 6),
     (N'Tiêu đề phản hồi 26', 'tieu-de-phan-hoi-26', 'Nội dung phản hồi 26', 1, 7),
     (N'Tiêu đề phản hồi 27', 'tieu-de-phan-hoi-27', 'Nội dung phản hồi 27', 2, 8),
     (N'Tiêu đề phản hồi 28', 'tieu-de-phan-hoi-28', 'Nội dung phản hồi 28', 1, 9),
     (N'Tiêu đề phản hồi 29', 'tieu-de-phan-hoi-29', 'Nội dung phản hồi 29', 2, 10),
     (N'Tiêu đề phản hồi 30', 'tieu-de-phan-hoi-30', 'Nội dung phản hồi 30', 2, 11),
     (N'Tiêu đề phản hồi 31', 'tieu-de-phan-hoi-31', 'Nội dung phản hồi 31', 1, 12),
     (N'Tiêu đề phản hồi 32', 'tieu-de-phan-hoi-32', 'Nội dung phản hồi 32', 1, 1),
     (N'Tiêu đề phản hồi 33', 'tieu-de-phan-hoi-33', 'Nội dung phản hồi 33', 1, 1),
     (N'Tiêu đề phản hồi 34', 'tieu-de-phan-hoi-34', 'Nội dung phản hồi 34', 1, 1),
     (N'Tiêu đề phản hồi 35', 'tieu-de-phan-hoi-35', 'Nội dung phản hồi 35', 1, 1),
     (N'Tiêu đề phản hồi 36', 'tieu-de-phan-hoi-36', 'Nội dung phản hồi 36', 1, 1),
     (N'Tiêu đề phản hồi 37', 'tieu-de-phan-hoi-37', 'Nội dung phản hồi 37', 1, 1),
     (N'Tiêu đề phản hồi 38', 'tieu-de-phan-hoi-38', 'Nội dung phản hồi 38', 1, 1),
     (N'Tiêu đề phản hồi 39', 'tieu-de-phan-hoi-39', 'Nội dung phản hồi 39', 2, 1),
     (N'Tiêu đề phản hồi 40', 'tieu-de-phan-hoi-40', 'Nội dung phản hồi 40', 2, 1),
     (N'Tiêu đề phản hồi 41', 'tieu-de-phan-hoi-41', 'Nội dung phản hồi 41', 2, 2),
     (N'Tiêu đề phản hồi 42', 'tieu-de-phan-hoi-42', 'Nội dung phản hồi 42', 1, 2),
     (N'Tiêu đề phản hồi 43', 'tieu-de-phan-hoi-43', 'Nội dung phản hồi 43', 1, 2),
     (N'Tiêu đề phản hồi 44', 'tieu-de-phan-hoi-44', 'Nội dung phản hồi 44', 1, 3),
     (N'Tiêu đề phản hồi 45', 'tieu-de-phan-hoi-45', 'Nội dung phản hồi 45', 1, 3),
     (N'Tiêu đề phản hồi 46', 'tieu-de-phan-hoi-46', 'Nội dung phản hồi 46', 1, 3),
     (N'Tiêu đề phản hồi 47', 'tieu-de-phan-hoi-47', 'Nội dung phản hồi 47', 1, 1),
     (N'Tiêu đề phản hồi 48', 'tieu-de-phan-hoi-48', 'Nội dung phản hồi 48', 1, 1),
     (N'Tiêu đề phản hồi 49', 'tieu-de-phan-hoi-49', 'Nội dung phản hồi 49', 1, 1),
     (N'Tiêu đề phản hồi 50', 'tieu-de-phan-hoi-50', 'Nội dung phản hồi 50', 1, 1),
     (N'Tiêu đề phản hồi 51', 'tieu-de-phan-hoi-51', 'Nội dung phản hồi 51', 1, 1),
     (N'Tiêu đề phản hồi 52', 'tieu-de-phan-hoi-52', 'Nội dung phản hồi 52', 2, 2),
     (N'Tiêu đề phản hồi 53', 'tieu-de-phan-hoi-53', 'Nội dung phản hồi 53', 2, 2),
     (N'Tiêu đề phản hồi 54', 'tieu-de-phan-hoi-54', 'Nội dung phản hồi 54', 2, 2),
     (N'Tiêu đề phản hồi 55', 'tieu-de-phan-hoi-55', 'Nội dung phản hồi 55', 1, 2),
     (N'Tiêu đề phản hồi 56', 'tieu-de-phan-hoi-56', 'Nội dung phản hồi 56', 1, 2),
     (N'Tiêu đề phản hồi 57', 'tieu-de-phan-hoi-57', 'Nội dung phản hồi 57', 1, 2),
     (N'Tiêu đề phản hồi 58', 'tieu-de-phan-hoi-58', 'Nội dung phản hồi 58', 1, 1),
     (N'Tiêu đề phản hồi 59', 'tieu-de-phan-hoi-59', 'Nội dung phản hồi 59', 2, 1),
     (N'Tiêu đề phản hồi 60', 'tieu-de-phan-hoi-60', 'Nội dung phản hồi 60', 2, 1),
     (N'Tiêu đề phản hồi 61', 'tieu-de-phan-hoi-61', 'Nội dung phản hồi 61', 2, 1),
     (N'Tiêu đề phản hồi 62', 'tieu-de-phan-hoi-62', 'Nội dung phản hồi 62', 2, 3),
     (N'Tiêu đề phản hồi 63', 'tieu-de-phan-hoi-63', 'Nội dung phản hồi 63', 1, 5),
     (N'Tiêu đề phản hồi 64', 'tieu-de-phan-hoi-64', 'Nội dung phản hồi 64', 1, 1),
     (N'Tiêu đề phản hồi 65', 'tieu-de-phan-hoi-65', 'Nội dung phản hồi 65', 1, 1),
     (N'Tiêu đề phản hồi 66', 'tieu-de-phan-hoi-66', 'Nội dung phản hồi 66', 5, 1),
     (N'Tiêu đề phản hồi 67', 'tieu-de-phan-hoi-67', 'Nội dung phản hồi 67', 2, 1),
     (N'Tiêu đề phản hồi 68', 'tieu-de-phan-hoi-68', 'Nội dung phản hồi 68', 1, 2),
     (N'Tiêu đề phản hồi 69', 'tieu-de-phan-hoi-69', 'Nội dung phản hồi 69', 1, 2),
     (N'Tiêu đề phản hồi 70', 'tieu-de-phan-hoi-70', 'Nội dung phản hồi 70', 1, 1),
     (N'Tiêu đề phản hồi 71', 'tieu-de-phan-hoi-71', 'Nội dung phản hồi 71', 2, 2),
     (N'Tiêu đề phản hồi 72', 'tieu-de-phan-hoi-72', 'Nội dung phản hồi 72', 1, 2),
     (N'Tiêu đề phản hồi 73', 'tieu-de-phan-hoi-73', 'Nội dung phản hồi 73', 1, 5),
     (N'Tiêu đề phản hồi 74', 'tieu-de-phan-hoi-74', 'Nội dung phản hồi 74', 2, 1);

INSERT
IGNORE INTO Post (title, slug, content, totalComment, totalEmotion, isEdited)
VALUES (N'Giới thiệu về hệ thống Habolabu', 'gioi-thieu-ve-he-thong-habolabu', 'Hệ thống Habolabu là một hệ thống quản lý dân cư', 4, 4, false),
    (N'Nội quy tại habolabu', 'noi-quy-tai-habolabu', 'Habolabu là nơi không có nội quy', 5, 5, false),
    (N'Ưu điểm của habolabu', 'uu-diem-cua-habolabu', 'Ưu điểm của Habolabu là không có khuyết điểm', 1, 1, true),
    (N'Nhược điểm của habolabu', 'nhuoc-diem-cua-habolabu', 'Nhược điểm của Habolabu là toàn ưu điểm', 1, 8, false),
    (N'Tiêu đề bài viết 1', 'tieu-de-bai-viet-1', 'Nội dung bài viết 1', 1, 8, true),
    (N'Tiêu đề bài viết 2', 'tieu-de-bai-viet-2', 'Nội dung bài viết 2', 1, 8, false),
    (N'Tiêu đề bài viết 3', 'tieu-de-bai-viet-3', 'Nội dung bài viết 3', 4, 8, true),
    (N'Tiêu đề bài viết 4', 'tieu-de-bai-viet-4', 'Nội dung bài viết 4', 3, 8, true),
    (N'Tiêu đề bài viết 5', 'tieu-de-bai-viet-5', 'Nội dung bài viết 5', 2, 8, true),
    (N'Tiêu đề bài viết 6', 'tieu-de-bai-viet-6', 'Nội dung bài viết 6', 1, 8, false),
    (N'Tiêu đề bài viết 7', 'tieu-de-bai-viet-7', 'Nội dung bài viết 7', 1, 8, true),
    (N'Tiêu đề bài viết 8', 'tieu-de-bai-viet-8', 'Nội dung bài viết 8', 1, 8, true),
    (N'Tiêu đề bài viết 9', 'tieu-de-bai-viet-9', 'Nội dung bài viết 9', 1, 8, true),
    (N'Tiêu đề bài viết 10', 'tieu-de-bai-viet-10', 'Nội dung bài viết 10', 1, 8, true),
    (N'Tiêu đề bài viết 11', 'tieu-de-bai-viet-11', 'Nội dung bài viết 11', 1, 8, false),
    (N'Tiêu đề bài viết 12', 'tieu-de-bai-viet-12', 'Nội dung bài viết 12', 1, 8, true),
    (N'Tiêu đề bài viết 13', 'tieu-de-bai-viet-13', 'Nội dung bài viết 13', 1, 8, true),
    (N'Tiêu đề bài viết 14', 'tieu-de-bai-viet-14', 'Nội dung bài viết 14', 1, 8, true),
    (N'Tiêu đề bài viết 15', 'tieu-de-bai-viet-15', 'Nội dung bài viết 15', 1, 8, true),
    (N'Tiêu đề bài viết 16', 'tieu-de-bai-viet-16', 'Nội dung bài viết 16', 2, 8, true),
    (N'Tiêu đề bài viết 17', 'tieu-de-bai-viet-17', 'Nội dung bài viết 17', 1, 8, true),
    (N'Tiêu đề bài viết 18', 'tieu-de-bai-viet-18', 'Nội dung bài viết 18', 4, 8, false),
    (N'Tiêu đề bài viết 19', 'tieu-de-bai-viet-19', 'Nội dung bài viết 19', 5, 8, true),
    (N'Tiêu đề bài viết 20', 'tieu-de-bai-viet-20', 'Nội dung bài viết 20', 2, 8, true),
    (N'Tiêu đề bài viết 21', 'tieu-de-bai-viet-21', 'Nội dung bài viết 21', 1, 8, true),
    (N'Tiêu đề bài viết 22', 'tieu-de-bai-viet-22', 'Nội dung bài viết 22', 5, 8, false),
    (N'Tiêu đề bài viết 23', 'tieu-de-bai-viet-23', 'Nội dung bài viết 23', 1, 8, true),
    (N'Tiêu đề bài viết 24', 'tieu-de-bai-viet-24', 'Nội dung bài viết 24', 1, 8, true),
    (N'Tiêu đề bài viết 25', 'tieu-de-bai-viet-25', 'Nội dung bài viết 25', 2, 8, false),
    (N'Tiêu đề bài viết 26', 'tieu-de-bai-viet-26', 'Nội dung bài viết 26', 1, 8, true),
    (N'Tiêu đề bài viết 27', 'tieu-de-bai-viet-27', 'Nội dung bài viết 27', 1, 8, false),
    (N'Tiêu đề bài viết 28', 'tieu-de-bai-viet-28', 'Nội dung bài viết 28', 5, 8, true),
    (N'Tiêu đề bài viết 29', 'tieu-de-bai-viet-29', 'Nội dung bài viết 29', 1, 8, true),
    (N'Tiêu đề bài viết 30', 'tieu-de-bai-viet-30', 'Nội dung bài viết 30', 1, 8, true),
    (N'Tiêu đề bài viết 31', 'tieu-de-bai-viet-31', 'Nội dung bài viết 31', 3, 8, true),
    (N'Tiêu đề bài viết 32', 'tieu-de-bai-viet-32', 'Nội dung bài viết 32', 1, 8, false),
    (N'Tiêu đề bài viết 33', 'tieu-de-bai-viet-33', 'Nội dung bài viết 33', 1, 8, true),
    (N'Tiêu đề bài viết 34', 'tieu-de-bai-viet-34', 'Nội dung bài viết 34', 1, 8, true),
    (N'Tiêu đề bài viết 35', 'tieu-de-bai-viet-35', 'Nội dung bài viết 35', 1, 8, true),
    (N'Tiêu đề bài viết 36', 'tieu-de-bai-viet-36', 'Nội dung bài viết 36', 1, 8, true),
    (N'Tiêu đề bài viết 37', 'tieu-de-bai-viet-37', 'Nội dung bài viết 37', 1, 8, false),
    (N'Tiêu đề bài viết 38', 'tieu-de-bai-viet-38', 'Nội dung bài viết 38', 1, 8, true),
    (N'Tiêu đề bài viết 39', 'tieu-de-bai-viet-39', 'Nội dung bài viết 39', 1, 8, false),
    (N'Tiêu đề bài viết 40', 'tieu-de-bai-viet-40', 'Nội dung bài viết 40', 1, 8, true),
    (N'Tiêu đề bài viết 41', 'tieu-de-bai-viet-41', 'Nội dung bài viết 41', 1, 8, true),
    (N'Tiêu đề bài viết 42', 'tieu-de-bai-viet-42', 'Nội dung bài viết 42', 1, 8, true),
    (N'Tiêu đề bài viết 43', 'tieu-de-bai-viet-43', 'Nội dung bài viết 43', 1, 8, true),
    (N'Tiêu đề bài viết 44', 'tieu-de-bai-viet-44', 'Nội dung bài viết 44', 1, 8, true),
    (N'Tiêu đề bài viết 45', 'tieu-de-bai-viet-45', 'Nội dung bài viết 45', 1, 8, true),
    (N'Tiêu đề bài viết 46', 'tieu-de-bai-viet-46', 'Nội dung bài viết 46', 1, 8, true),
    (N'Tiêu đề bài viết 47', 'tieu-de-bai-viet-47', 'Nội dung bài viết 47', 1, 8, false);

INSERT
IGNORE INTO Emotion (name, icon)
VALUES (N'Thích', 'https://res.cloudinary.com/dzd9sonxs/image/upload/v1672239478/emoji/like_uxq9ok.svg'),
    (N'Tim', 'https://res.cloudinary.com/dzd9sonxs/image/upload/v1672239478/emoji/love_vhjhlb.svg'),
    (N'Thương thương', 'https://res.cloudinary.com/dzd9sonxs/image/upload/v1672239479/emoji/care_rjzmav.svg'),
    (N'Haha', 'https://res.cloudinary.com/dzd9sonxs/image/upload/v1672239478/emoji/haha_hwgo3u.svg'),
    (N'Wow', 'https://res.cloudinary.com/dzd9sonxs/image/upload/v1672239477/emoji/wow_jmezta.svg'),
    (N'Buồn', 'https://res.cloudinary.com/dzd9sonxs/image/upload/v1672239478/emoji/sad_ttzf24.svg'),
    (N'Giận dữ', 'https://res.cloudinary.com/dzd9sonxs/image/upload/v1672239478/emoji/angry_voavkr.svg');

INSERT
IGNORE INTO Comment (content, totalEmotion, userId, postId, commentId)
VALUES (N'Ú là trời!', 3, 1, 1, NULL),
    (N'Quá tuyệt vời', 2, 2, 1, 1),
    (N'Hảo hảo 100', 4, 3, 1, 1),
    (N'Hảo hảo chua cay', 2, 5, 1, 2),
    (N'wán đờ phùn', 4, 1, 2, NULL),
    (N'wán đờ phèng', 2, 2, 2, 5),
    (N'wán đờ phàng', 0, 3, 2, 5),
    (N'wán đờ phìn', 0, 2, 2, NULL),
    (N'wán đờ phồng', 1, 5, 2, 8),
    (N'ahihi', 1, 1, 3, NULL),
    (N'ahoho', 0, 1, 4, NULL),
    (N'Nội dung bình luận 1', 0, 1, 1, NULL),
    (N'Nội dung bình luận 2', 0, 1, 2, NULL),
    (N'Nội dung bình luận 3', 0, 1, 3, NULL),
    (N'Nội dung bình luận 4', 0, 1, 4, NULL),
    (N'Nội dung bình luận 5', 0, 1, 5, NULL),
    (N'Nội dung bình luận 6', 0, 1, 6, NULL),
    (N'Nội dung bình luận 7', 0, 1, 7, NULL),
    (N'Nội dung bình luận 8', 0, 1, 8, NULL),
    (N'Nội dung bình luận 9', 0, 1, 1, NULL),
    (N'Nội dung bình luận 10', 0, 1, 1, NULL),
    (N'Nội dung bình luận 11', 0, 1, 1, NULL),
    (N'Nội dung bình luận 12', 0, 1, 1, NULL),
    (N'Nội dung bình luận 13', 0, 1, 1, NULL),
    (N'Nội dung bình luận 14', 0, 1, 1, NULL),
    (N'Nội dung bình luận 15', 0, 1, 3, NULL),
    (N'Nội dung bình luận 16', 0, 1, 4, NULL),
    (N'Nội dung bình luận 17', 0, 1, 5, NULL),
    (N'Nội dung bình luận 18', 0, 1, 6, NULL),
    (N'Nội dung bình luận 19', 0, 1, 7, NULL),
    (N'Nội dung bình luận 20', 0, 1, 8, NULL),
    (N'Nội dung bình luận 21', 0, 1, 9, NULL),
    (N'Nội dung bình luận 22', 0, 1, 10, NULL),
    (N'Nội dung bình luận 23', 0, 1, 1, NULL),
    (N'Nội dung bình luận 24', 0, 1, 1, NULL),
    (N'Nội dung bình luận 25', 0, 1, 1, NULL),
    (N'Nội dung bình luận 26', 0, 1, 1, NULL),
    (N'Nội dung bình luận 27', 0, 1, 1, NULL),
    (N'Nội dung bình luận 28', 0, 1, 2, NULL),
    (N'Nội dung bình luận 29', 0, 1, 2, NULL),
    (N'Nội dung bình luận 30', 0, 1, 2, NULL),
    (N'Nội dung bình luận 31', 0, 1, 2, NULL),
    (N'Nội dung bình luận 32', 0, 1, 2, NULL),
    (N'Nội dung bình luận 33', 0, 1, 2, NULL),
    (N'Nội dung bình luận 34', 0, 1, 1, NULL),
    (N'Nội dung bình luận 35', 0, 1, 1, NULL),
    (N'Nội dung bình luận 36', 0, 1, 1, NULL),
    (N'Nội dung bình luận 37', 0, 1, 1, NULL),
    (N'Nội dung bình luận 38', 0, 1, 1, NULL),
    (N'Nội dung bình luận 39', 0, 1, 1, NULL),
    (N'Nội dung bình luận 40', 0, 1, 1, NULL),
    (N'Nội dung bình luận 41', 0, 1, 1, NULL),
    (N'Nội dung bình luận 42', 0, 1, 1, NULL),
    (N'Nội dung bình luận 43', 0, 1, 1, NULL),
    (N'Nội dung bình luận 44', 0, 1, 1, NULL),
    (N'Nội dung bình luận 45', 0, 1, 1, NULL),
    (N'Nội dung bình luận 46', 0, 1, 1, NULL),
    (N'Nội dung bình luận 47', 0, 1, 1, NULL),
    (N'Nội dung bình luận 48', 0, 1, 3, NULL),
    (N'Nội dung bình luận 49', 0, 1, 1, NULL),
    (N'Nội dung bình luận 50', 0, 1, 1, NULL),
    (N'Nội dung bình luận 51', 0, 1, 1, NULL),
    (N'Nội dung bình luận 52', 0, 1, 1, NULL);

INSERT
IGNORE INTO CommentEmotion (commentId, userId, emotionId)
VALUES (1,1,1),
    (2,2,2),
    (3,3,3),
    (4,4,4),
    (5,5,5),
    (6,6,6),
    (7,7,7),
    (8,8,1),
    (9,9,2),
    (10,10,3),
    (11,1,4),
    (1,2,5),
    (2,3,6),
    (3,4,7),
    (4,5,1),
    (5,6,2),
    (6,7,3),
    (7,8,4),
    (8,9,5);

INSERT
IGNORE INTO PostEmotion (postId, userId, emotionId)
VALUES (1, 1, 1),
    (1, 2, 2),
    (1, 3, 3),
    (1, 4, 4),
    (2, 1, 5),
    (2, 2, 6),
    (2, 3, 7),
    (2, 4, 1),
    (2, 5, 1),
    (3, 1, 2),
    (4, 2, 3),
    (4, 3, 4),
    (4, 4, 5),
    (4, 5, 6),
    (4, 6, 7),
    (4, 7, 1),
    (4, 8, 2),
    (4, 9, 3);