-- liquibase formatted sql
-- 2023-02-13 21:00:00 VN
-- changeset trungkien.nguyen:V202302130921_add_permission_table_data

INSERT INTO Service (name)
VALUES ('Activity'),
       ('Auth'),
       ('Building'),
       ('Human'),
       ('Payment');

UPDATE Role
SET name = 'ADMINISTRATOR', display = 'ADMINISTRATOR'
WHERE name = 'quan-tri-vien';

UPDATE Role
SET name = 'NORMAL_USER', display = 'NORMAL USER'
WHERE name = 'nguoi-dung-thuong';

INSERT INTO Permission (name, display, parentId, childOrder, type, serviceId)
VALUES ('COMMENT_PERMISSIONS', 'COMMENT PERMISSIONS', NULL, 1, 'label', 1),
       ('VIEW_COMMENT', 'VIEW COMMENT', 1, 1, 'permission', 1),
       ('ADD_NEW_COMMENT', 'ADD NEW COMMENT', 1, 2, 'permission', 1),
       ('DELETE_EXIST_COMMENT', 'DELETE EXIST COMMENT', 1, 3, 'permission', 1),
       ('MODIFY_EXIST_COMMENT', 'MODIFY EXIST COMMENT', 1, 4, 'permission', 1),
       ('VIEW_COMMENT_EMOTION', 'VIEW COMMENT EMOTION', 1, 5, 'permission', 1),
       ('REACT_EXIST_COMMENT', 'REACT EXIST COMMENT', 1, 6, 'permission', 1),
       ('REMOVE_COMMENT_REACTION', 'REMOVE COMMENT REACTION', 1, 7, 'permission', 1),
       ('EMOTION_PERMISSIONS', 'EMOTION PERMISSIONS', NULL, 2, 'label', 1),
       ('VIEW_EMOTION', 'VIEW EMOTION', 9, 1, 'permission', 1),
       ('ADD_NEW_EMOTION', 'ADD NEW EMOTION', 9, 2, 'permission', 1),
       ('DELETE_EXIST_EMOTION', 'DELETE EXIST EMOTION', 9, 3, 'permission', 1),
       ('MODIFY_EXIST_EMOTION', 'MODIFY EXIST EMOTION', 9, 4, 'permission', 1),
       ('FEEDBACK_PERMISSIONS', 'FEEDBACK PERMISSIONS', NULL, 3, 'label', 1),
       ('VIEW_FEEDBACK', 'VIEW FEEDBACK', 14, 1, 'permission', 1),
       ('ADD_NEW_FEEDBACK', 'ADD NEW FEEDBACK', 14, 2, 'permission', 1),
       ('DELETE_EXIST_FEEDBACK', 'DELETE EXIST FEEDBACK', 14, 3, 'permission', 1),
       ('MODIFY_EXIST_FEEDBACK', 'MODIFY EXIST FEEDBACK', 14, 4, 'permission', 1),
       ('FEEDBACK_TYPE_PERMISSIONS', 'FEEDBACK TYPE PERMISSIONS', NULL, 4, 'label', 1),
       ('VIEW_FEEDBACK_TYPE', 'VIEW FEEDBACK TYPE', 19, 1, 'permission', 1),
       ('ADD_NEW_FEEDBACK_TYPE', 'ADD NEW FEEDBACK TYPE', 19, 2, 'permission', 1),
       ('DELETE_EXIST_FEEDBACK_TYPE', 'DELETE EXIST FEEDBACK TYPE', 19, 3, 'permission', 1),
       ('MODIFY_EXIST_FEEDBACK_TYPE', 'MODIFY EXIST FEEDBACK TYPE', 19, 4, 'permission', 1),
       ('POST_PERMISSIONS', 'POST PERMISSIONS', NULL, 5, 'label', 1),
       ('VIEW_POST', 'VIEW POST', 24, 1, 'permission', 1),
       ('ADD_NEW_POST', 'ADD NEW POST', 24, 2, 'permission', 1),
       ('DELETE_EXIST_POST', 'DELETE EXIST POST', 24, 3, 'permission', 1),
       ('MODIFY_EXIST_POST', 'MODIFY EXIST POST', 24, 4, 'permission', 1),
       ('VIEW_POST_EMOTION', 'VIEW POST_EMOTION', 24, 5, 'permission', 1),
       ('REACT_EXIST_POST', 'REACT EXIST POST', 24, 6, 'permission', 1),
       ('REMOVE_POST_REACTION', 'REMOVE POST REACTION', 24, 7, 'permission', 1),
       ('PASSWORD_PERMISSIONS', 'PASSWORD PERMISSIONS', NULL, 1, 'label', 2),
       ('ADD_NEW_PASSWORD', 'ADD NEW PASSWORD', 32, 1, 'permission', 2),
       ('ROLE_PERMISSIONS', 'ROLE PERMISSIONS', NULL, 2, 'label', 2),
       ('VIEW_ROLE', 'VIEW ROLE', 34, 1, 'permission', 2),
       ('ADD_NEW_ROLE', 'ADD NEW ROLE', 34, 2, 'permission', 2),
       ('DELETE_EXIST_ROLE', 'DELETE EXIST ROLE', 34, 3, 'permission', 2),
       ('MODIFY_EXIST_ROLE', 'MODIFY EXIST ROLE', 34, 4, 'permission', 2),
       ('VIEW_PERMISSION', 'VIEW PERMISSION', 34, 5, 'permission', 2),
       ('GRANT_PERMISSION', 'GRANT PERMISSION', 34, 6, 'permission', 2),
       ('APARTMENT_PERMISSIONS', 'APARTMENT PERMISSIONS', NULL, 1, 'label', 3),
       ('VIEW_APARTMENT', 'VIEW APARTMENT', 41, 1, 'permission', 3),
       ('ADD_NEW_APARTMENT', 'ADD NEW APARTMENT', 41, 2, 'permission', 3),
       ('DELETE_EXIST_APARTMENT', 'DELETE EXIST APARTMENT', 41, 3, 'permission', 3),
       ('MODIFY_EXIST_APARTMENT', 'MODIFY EXIST APARTMENT', 41, 4, 'permission', 3),
       ('AREA_PERMISSIONS', 'AREA PERMISSIONS', NULL, 2, 'label', 3),
       ('VIEW_AREA', 'VIEW AREA', 46, 1, 'permission', 3),
       ('ADD_NEW_AREA', 'ADD NEW AREA', 46, 2, 'permission', 3),
       ('DELETE_EXIST_AREA', 'DELETE EXIST AREA', 46, 3, 'permission', 3),
       ('MODIFY_EXIST_AREA', 'MODIFY EXIST AREA', 46, 4, 'permission', 3),
       ('OWNER_HISTORY_PERMISSIONS', 'OWNER HISTORY PERMISSIONS', NULL, 3, 'label', 3),
       ('ADD_NEW_OWNER_HISTORY', 'ADD NEW OWNER HISTORY', 51, 1, 'permission', 3),
       ('DELETE_EXIST_OWNER_HISTORY', 'DELETE EXIST OWNER HISTORY', 51, 2, 'permission', 3),
       ('MODIFY_EXIST_OWNER_HISTORY', 'MODIFY EXIST OWNER HISTORY', 51, 3, 'permission', 3),
       ('PARKING_PERMISSIONS', 'PARKING PERMISSIONS', NULL, 4, 'label', 3),
       ('VIEW_PARKING', 'VIEW PARKING', 55, 1, 'permission', 3),
       ('ADD_NEW_PARKING', 'ADD NEW PARKING', 55, 2, 'permission', 3),
       ('DELETE_EXIST_PARKING', 'DELETE EXIST PARKING', 55, 3, 'permission', 3),
       ('MODIFY_EXIST_PARKING', 'MODIFY EXIST PARKING', 55, 4, 'permission', 3),
       ('PARKING_SPACE_PERMISSIONS', 'PARKING SPACE PERMISSIONS', NULL, 5, 'label', 3),
       ('VIEW_PARKING_SPACE', 'VIEW PARKING SPACE', 60, 1, 'permission', 3),
       ('ADD_NEW_PARKING_SPACE', 'ADD NEW PARKING SPACE', 60, 2, 'permission', 3),
       ('DELETE_EXIST_PARKING_SPACE', 'DELETE EXIST PARKING SPACE', 60, 3, 'permission', 3),
       ('MODIFY_EXIST_PARKING_SPACE', 'MODIFY EXIST PARKING SPACE', 60, 4, 'permission', 3),
       ('PARKING_TYPE_PERMISSIONS', 'PARKING TYPE PERMISSIONS', NULL, 6, 'label', 3),
       ('VIEW_PARKING_TYPE', 'VIEW PARKING TYPE', 65, 1, 'permission', 3),
       ('ADD_NEW_PARKING_TYPE', 'ADD NEW PARKING TYPE', 65, 2, 'permission', 3),
       ('DELETE_EXIST_PARKING_TYPE', 'DELETE EXIST PARKING TYPE', 65, 3, 'permission', 3),
       ('MODIFY_EXIST_PARKING_TYPE', 'MODIFY EXIST PARKING TYPE', 65, 4, 'permission', 3),
       ('PRICE_TAG_PERMISSIONS', 'PRICE TAG PERMISSIONS', NULL, 7, 'label', 3),
       ('VIEW_PRICE_TAG', 'VIEW PRICE TAG', 70, 1, 'permission', 3),
       ('ADD_NEW_PRICE_TAG', 'ADD NEW PRICE TAG', 70, 2, 'permission', 3),
       ('DELETE_EXIST_PRICE_TAG', 'DELETE EXIST PRICE TAG', 70, 3, 'permission', 3),
       ('MODIFY_EXIST_PRICE_TAG', 'MODIFY EXIST PRICE TAG', 70, 4, 'permission', 3),
       ('ROOM_PERMISSIONS', 'ROOM PERMISSIONS', NULL, 8, 'label', 3),
       ('VIEW_ROOM', 'VIEW ROOM', 75, 1, 'permission', 3),
       ('ADD_NEW_ROOM', 'ADD NEW ROOM', 75, 2, 'permission', 3),
       ('DELETE_EXIST_ROOM', 'DELETE EXIST ROOM', 75, 3, 'permission', 3),
       ('MODIFY_EXIST_ROOM', 'MODIFY EXIST ROOM', 75, 4, 'permission', 3),
       ('AVATAR_PERMISSIONS', 'AVATAR PERMISSIONS', NULL, 1, 'label', 4),
       ('VIEW_AVATAR', 'VIEW AVATAR', 80, 1, 'permission', 4),
       ('ADD_NEW_AVATAR', 'ADD NEW AVATAR', 80, 2, 'permission', 4),
       ('DELETE_EXIST_AVATAR', 'DELETE EXIST AVATAR', 80, 3, 'permission', 4),
       ('MODIFY_EXIST_AVATAR', 'MODIFY EXIST AVATAR', 80, 4, 'permission', 4),
       ('EMERGENCY_PERMISSIONS', 'EMERGENCY PERMISSIONS', NULL, 2, 'label', 4),
       ('VIEW_EMERGENCY', 'VIEW EMERGENCY', 85, 1, 'permission', 4),
       ('ADD_NEW_EMERGENCY', 'ADD NEW EMERGENCY', 85, 2, 'permission', 4),
       ('DELETE_EXIST_EMERGENCY', 'DELETE EXIST EMERGENCY', 85, 3, 'permission', 4),
       ('MODIFY_EXIST_EMERGENCY', 'MODIFY EXIST EMERGENCY', 85, 4, 'permission', 4),
       ('PARKING_DETAIL_PERMISSIONS', 'PARKING DETAIL PERMISSIONS', NULL, 3, 'label', 4),
       ('VIEW_PARKING_DETAIL', 'VIEW PARKING DETAIL', 90, 1, 'permission', 4),
       ('ADD_NEW_PARKING_DETAIL', 'ADD NEW PARKING DETAIL', 90, 2, 'permission', 4),
       ('DELETE_EXIST_PARKING_DETAIL', 'DELETE EXIST PARKING DETAIL', 90, 3, 'permission', 4),
       ('ROOM_DETAIL_PERMISSIONS', 'ROOM DETAIL PERMISSIONS', NULL, 4, 'label', 4),
       ('VIEW_ROOM_DETAIL', 'VIEW ROOM DETAIL', 94, 1, 'permission', 4),
       ('ADD_NEW_ROOM_DETAIL', 'ADD NEW ROOM DETAIL', 94, 2, 'permission', 4),
       ('DELETE_EXIST_ROOM_DETAIL', 'DELETE EXIST ROOM DETAIL', 94, 3, 'permission', 4),
       ('USER_PERMISSIONS', 'USER PERMISSIONS', NULL, 5, 'label', 4),
       ('VIEW_USER', 'VIEW USER', 98, 1, 'permission', 4),
       ('ADD_NEW_USER', 'ADD NEW USER', 98, 2, 'permission', 4),
       ('DELETE_EXIST_USER', 'DELETE EXIST USER', 98, 3, 'permission', 4),
       ('MODIFY_EXIST_USER', 'MODIFY EXIST USER', 98, 4, 'permission', 4),
       ('BILL_PERMISSIONS', 'BILL PERMISSIONS', NULL, 1, 'label', 5),
       ('VIEW_BILL', 'VIEW BILL', 103, 1, 'permission', 5),
       ('STATISTIC', 'STATISTIC', 103, 2, 'permission', 5),
       ('APPROVE_BILL', 'APPROVE BILL', 103, 3, 'permission', 5),
       ('REJECT_BILL', 'REJECT BILL', 103, 4, 'permission', 5);

INSERT INTO AccountSetting (accountId, roleId, permissionId, status)
VALUES (1, 1, 2, true),
       (1, 1, 3, true),
       (1, 1, 4, true),
       (1, 1, 5, true),
       (1, 1, 6, true),
       (1, 1, 7, true),
       (1, 1, 8, true),
       (1, 1, 10, true),
       (1, 1, 11, true),
       (1, 1, 12, true),
       (1, 1, 13, true),
       (1, 1, 15, true),
       (1, 1, 16, true),
       (1, 1, 17, true),
       (1, 1, 18, true),
       (1, 1, 20, true),
       (1, 1, 21, true),
       (1, 1, 22, true),
       (1, 1, 23, true),
       (1, 1, 25, true),
       (1, 1, 26, true),
       (1, 1, 27, true),
       (1, 1, 28, true),
       (1, 1, 29, true),
       (1, 1, 30, true),
       (1, 1, 31, true),
       (1, 1, 33, true),
       (1, 1, 35, true),
       (1, 1, 36, true),
       (1, 1, 37, true),
       (1, 1, 38, true),
       (1, 1, 39, true),
       (1, 1, 40, true),
       (1, 1, 42, true),
       (1, 1, 43, true),
       (1, 1, 44, true),
       (1, 1, 45, true),
       (1, 1, 47, true),
       (1, 1, 48, true),
       (1, 1, 49, true),
       (1, 1, 50, true),
       (1, 1, 52, true),
       (1, 1, 53, true),
       (1, 1, 54, true),
       (1, 1, 56, true),
       (1, 1, 57, true),
       (1, 1, 58, true),
       (1, 1, 59, true),
       (1, 1, 61, true),
       (1, 1, 62, true),
       (1, 1, 63, true),
       (1, 1, 64, true),
       (1, 1, 66, true),
       (1, 1, 67, true),
       (1, 1, 68, true),
       (1, 1, 69, true),
       (1, 1, 71, true),
       (1, 1, 72, true),
       (1, 1, 73, true),
       (1, 1, 74, true),
       (1, 1, 76, true),
       (1, 1, 77, true),
       (1, 1, 78, true),
       (1, 1, 79, true),
       (1, 1, 81, true),
       (1, 1, 82, true),
       (1, 1, 83, true),
       (1, 1, 84, true),
       (1, 1, 86, true),
       (1, 1, 87, true),
       (1, 1, 88, true),
       (1, 1, 89, true),
       (1, 1, 91, true),
       (1, 1, 92, true),
       (1, 1, 93, true),
       (1, 1, 95, true),
       (1, 1, 96, true),
       (1, 1, 97, true),
       (1, 1, 99, true),
       (1, 1, 100, true),
       (1, 1, 101, true),
       (1, 1, 102, true),
       (2, 2, 2, true),
       (2, 2, 3, true),
       (2, 2, 4, true),
       (2, 2, 5, true),
       (2, 2, 6, true),
       (2, 2, 7, true),
       (2, 2, 8, true),
       (2, 2, 10, false),
       (2, 2, 11, false),
       (2, 2, 12, false),
       (2, 2, 13, false),
       (2, 2, 15, false),
       (2, 2, 16, true),
       (2, 2, 17, false),
       (2, 2, 18, false),
       (2, 2, 20, true),
       (2, 2, 21, false),
       (2, 2, 22, false),
       (2, 2, 23, false),
       (2, 2, 25, true),
       (2, 2, 26, false),
       (2, 2, 27, false),
       (2, 2, 28, false),
       (2, 2, 29, true),
       (2, 2, 30, true),
       (2, 2, 31, true),
       (2, 2, 33, true),
       (2, 2, 35, false),
       (2, 2, 36, false),
       (2, 2, 37, false),
       (2, 2, 38, false),
       (2, 2, 39, false),
       (2, 2, 40, false),
       (2, 2, 42, false),
       (2, 2, 43, false),
       (2, 2, 44, false),
       (2, 2, 45, false),
       (2, 2, 47, false),
       (2, 2, 48, false),
       (2, 2, 49, false),
       (2, 2, 50, false),
       (2, 2, 52, false),
       (2, 2, 53, false),
       (2, 2, 54, false),
       (2, 2, 56, false),
       (2, 2, 57, false),
       (2, 2, 58, false),
       (2, 2, 59, false),
       (2, 2, 61, false),
       (2, 2, 62, false),
       (2, 2, 63, false),
       (2, 2, 64, false),
       (2, 2, 66, false),
       (2, 2, 67, false),
       (2, 2, 68, false),
       (2, 2, 69, false),
       (2, 2, 71, false),
       (2, 2, 72, false),
       (2, 2, 73, false),
       (2, 2, 74, false),
       (2, 2, 76, false),
       (2, 2, 77, false),
       (2, 2, 78, false),
       (2, 2, 79, false),
       (2, 2, 81, true),
       (2, 2, 82, true),
       (2, 2, 83, true),
       (2, 2, 84, true),
       (2, 2, 86, true),
       (2, 2, 87, true),
       (2, 2, 88, true),
       (2, 2, 89, true),
       (2, 2, 91, false),
       (2, 2, 92, false),
       (2, 2, 93, false),
       (2, 2, 95, false),
       (2, 2, 96, false),
       (2, 2, 97, false),
       (2, 2, 99, false),
       (2, 2, 100, false),
       (2, 2, 101, false),
       (2, 2, 102, false);