version: "1.0"

volumes:
  cli_service_data:
  cli_gradle_data:

networks:
  command_database_net:
    external: true
  query_database_net:
    external: true

services:
  cli:
    container_name: "cli-service"
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    ports:
      - ${CLI_SERVICE_HOST_PORT}:${CLI_SERVICE_CONTAINER_PORT}
    volumes:
      - cli_service_data:${CLI_SERVICE_VOLUMES}
      - cli_gradle_data:${CLI_GRADLE_VOLUMES}
    networks:
      - command_database_net
      - query_database_net
    env_file:
      - .env
    restart: on-failure
    environment:
      SERVER_PORT: ${SERVER_PORT}
      AUTH_GROUP_COMMAND_URL: ${AUTH_GROUP_COMMAND_URL}
      AUTH_GROUP_COMMAND_USERNAME: ${AUTH_GROUP_COMMAND_USERNAME}
      AUTH_GROUP_COMMAND_PASSWORD: ${AUTH_GROUP_COMMAND_PASSWORD}
      AUTH_GROUP_COMMAND_DRIVER_CLASS_NAME: ${AUTH_GROUP_COMMAND_DRIVER_CLASS_NAME}
      AUTH_GROUP_COMMAND_LIQUIBASE_ENABLED: ${AUTH_GROUP_COMMAND_LIQUIBASE_ENABLED}
      AUTH_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG: ${AUTH_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG}
      AUTH_GROUP_QUERY_URL: ${AUTH_GROUP_QUERY_URL}
      AUTH_GROUP_QUERY_LIQUIBASE_CHANGE_LOG: ${AUTH_GROUP_QUERY_LIQUIBASE_CHANGE_LOG}
      BUILDING_GROUP_COMMAND_URL: ${BUILDING_GROUP_COMMAND_URL}
      BUILDING_GROUP_COMMAND_USERNAME: ${BUILDING_GROUP_COMMAND_USERNAME}
      BUILDING_GROUP_COMMAND_PASSWORD: ${BUILDING_GROUP_COMMAND_PASSWORD}
      BUILDING_GROUP_COMMAND_DRIVER_CLASS_NAME: ${BUILDING_GROUP_COMMAND_DRIVER_CLASS_NAME}
      BUILDING_GROUP_COMMAND_LIQUIBASE_ENABLED: ${BUILDING_GROUP_COMMAND_LIQUIBASE_ENABLED}
      BUILDING_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG: ${BUILDING_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG}
      BUILDING_GROUP_QUERY_URL: ${BUILDING_GROUP_QUERY_URL}
      BUILDING_GROUP_QUERY_LIQUIBASE_CHANGE_LOG: ${BUILDING_GROUP_QUERY_LIQUIBASE_CHANGE_LOG}
      HUMAN_GROUP_COMMAND_URL: ${HUMAN_GROUP_COMMAND_URL}
      HUMAN_GROUP_COMMAND_USERNAME: ${HUMAN_GROUP_COMMAND_USERNAME}
      HUMAN_GROUP_COMMAND_PASSWORD: ${HUMAN_GROUP_COMMAND_PASSWORD}
      HUMAN_GROUP_COMMAND_DRIVER_CLASS_NAME: ${HUMAN_GROUP_COMMAND_DRIVER_CLASS_NAME}
      HUMAN_GROUP_COMMAND_LIQUIBASE_ENABLED: ${HUMAN_GROUP_COMMAND_LIQUIBASE_ENABLED}
      HUMAN_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG: ${HUMAN_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG}
      HUMAN_GROUP_QUERY_URL: ${HUMAN_GROUP_QUERY_URL}
      HUMAN_GROUP_QUERY_LIQUIBASE_CHANGE_LOG: ${HUMAN_GROUP_QUERY_LIQUIBASE_CHANGE_LOG}
      PAYMENT_GROUP_COMMAND_URL: ${PAYMENT_GROUP_COMMAND_URL}
      PAYMENT_GROUP_COMMAND_USERNAME: ${PAYMENT_GROUP_COMMAND_USERNAME}
      PAYMENT_GROUP_COMMAND_PASSWORD: ${PAYMENT_GROUP_COMMAND_PASSWORD}
      PAYMENT_GROUP_COMMAND_DRIVER_CLASS_NAME: ${PAYMENT_GROUP_COMMAND_DRIVER_CLASS_NAME}
      PAYMENT_GROUP_COMMAND_LIQUIBASE_ENABLED: ${PAYMENT_GROUP_COMMAND_LIQUIBASE_ENABLED}
      PAYMENT_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG: ${PAYMENT_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG}
      PAYMENT_GROUP_QUERY_URL: ${PAYMENT_GROUP_QUERY_URL}
      PAYMENT_GROUP_QUERY_LIQUIBASE_CHANGE_LOG: ${PAYMENT_GROUP_QUERY_LIQUIBASE_CHANGE_LOG}
      ACTIVITY_GROUP_COMMAND_URL: ${ACTIVITY_GROUP_COMMAND_URL}
      ACTIVITY_GROUP_COMMAND_USERNAME: ${ACTIVITY_GROUP_COMMAND_USERNAME}
      ACTIVITY_GROUP_COMMAND_PASSWORD: ${ACTIVITY_GROUP_COMMAND_PASSWORD}
      ACTIVITY_GROUP_COMMAND_DRIVER_CLASS_NAME: ${ACTIVITY_GROUP_COMMAND_DRIVER_CLASS_NAME}
      ACTIVITY_GROUP_COMMAND_LIQUIBASE_ENABLED: ${ACTIVITY_GROUP_COMMAND_LIQUIBASE_ENABLED}
      ACTIVITY_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG: ${ACTIVITY_GROUP_COMMAND_LIQUIBASE_CHANGE_LOG}
      ACTIVITY_GROUP_QUERY_URL: ${ACTIVITY_GROUP_QUERY_URL}
      ACTIVITY_GROUP_QUERY_LIQUIBASE_CHANGE_LOG: ${ACTIVITY_GROUP_QUERY_LIQUIBASE_CHANGE_LOG}
